spring.application.name=OnlineBankingSystem-1
spring.datasource.url=jdbc:mysql://localhost:3306/onlinebank_db
spring.datasource.username=root
spring.datasource.password=chen919191

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true